apiVersion: v1
kind: Service
metadata:
    name: sql-server
    labels:
       name: sql-server
spec:
   selector:
        name: mysql-env
   ports:
      - port: 3306
        protocol: TCP
        targetPort: 3306
   type: ClusterIP
   ClusterIP: None
