apiVersion: v1
kind: Service
metadata:
    name: http-server
    labels:
      run: http-server
spec:
   selector:
        name: http-server
   ports:
      - name: website
        port: 80
        protocol: TCP
        targetPort: 80
   type: LoadBalancer
